/* Stock photos/videos for Cipher Studio. API keys stay in local settings and
   are sent only to the licensed localhost proxy; selected files are persisted
   as project Blobs by the existing ProTimeline/Projects pipeline. */
window.StockMedia=(function(){
  const results=new Map();let page=1,lastQuery='',busy=false;
  const $=id=>document.getElementById(id);
  const escape=value=>String(value||'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));
  const keys=()=>window.AI?.getKeys?.()||{};
  function init(){
    $('btn-project-media-view')?.addEventListener('click',()=>showPane('project'));
    $('btn-stock-media-view')?.addEventListener('click',()=>showPane('stock'));
    $('btn-stock-search')?.addEventListener('click',()=>search(false));
    $('btn-stock-load-more')?.addEventListener('click',()=>search(true));
    $('stock-search-query')?.addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();search(false);}});
    $('stock-media-type')?.addEventListener('change',syncDurationFilter);
    syncDurationFilter();refreshKeyNotice();
  }
  function showPane(name){const stock=name==='stock';$('project-media-pane')?.classList.toggle('active',!stock);$('stock-media-pane')?.classList.toggle('active',stock);$('btn-project-media-view')?.classList.toggle('active',!stock);$('btn-stock-media-view')?.classList.toggle('active',stock);if(stock)refreshKeyNotice();}
  function refreshKeyNotice(){const current=keys(),notice=$('stock-key-notice'),available=[current.pexels&&'Pexels',current.pixabay&&'Pixabay'].filter(Boolean);if(!notice)return;notice.classList.toggle('ready',available.length>0);notice.innerHTML=available.length?`Ready: <strong>${available.join(' + ')}</strong> keys are stored locally.`:`Add a free Pexels or Pixabay API key in <button type="button" data-stock-settings>Settings</button>.`;notice.querySelector('[data-stock-settings]')?.addEventListener('click',()=>window.openAiSettingsModal?.());}
  function syncDurationFilter(){$('stock-video-duration')?.closest('label')?.classList.toggle('hidden',$('stock-media-type')?.value!=='videos');}
  function setStatus(message,error=false){const box=$('stock-media-status');if(box){box.textContent=message||'';box.classList.toggle('error',error);}}
  function durationAllowed(item,filter){if(item.type!=='video'||filter==='any')return true;const seconds=Number(item.duration)||0;if(!seconds)return true;return filter==='short'?seconds<=15:filter==='medium'?seconds>15&&seconds<=60:seconds>60;}
  async function search(loadMore=false){
    if(busy)return;const query=String($('stock-search-query')?.value||'').trim(),source=$('stock-media-source')?.value||'both',current=keys();if(!query){setStatus('Enter a search term.',true);return;}if(source==='pexels'&&!current.pexels){setStatus('Add your Pexels API key in Settings.',true);return;}if(source==='pixabay'&&!current.pixabay){setStatus('Add your Pixabay API key in Settings.',true);return;}if(source==='both'&&!current.pexels&&!current.pixabay){setStatus('Add a free Pexels or Pixabay API key in Settings.',true);return;}
    busy=true;page=loadMore&&query===lastQuery?page+1:1;lastQuery=query;$('btn-stock-search').disabled=true;setStatus(`Searching ${$('stock-media-type').value}…`);
    try{const params=new URLSearchParams({query,source,type:$('stock-media-type').value,orientation:$('stock-media-orientation').value,resolution:$('stock-media-resolution').value,page:String(page),per_page:'24'}),response=await fetch(`/api/stock-media/search?${params}`,{headers:{'X-Pexels-Key':current.pexels||'','X-Pixabay-Key':current.pixabay||''}}),data=await response.json().catch(()=>({}));if(!response.ok||!data.success)throw new Error(data.error||'Stock media search failed.');let items=(data.results||[]).filter(item=>durationAllowed(item,$('stock-video-duration').value));items.forEach(item=>results.set(item.id,item));render(items,loadMore);setStatus(`${loadMore?'Added':'Found'} ${items.length} result${items.length===1?'':'s'}${data.warnings?.length?' • '+data.warnings.join(' '):''}`);$('btn-stock-load-more')?.classList.toggle('hidden',items.length===0);}catch(error){if(!loadMore)$('stock-media-results').innerHTML='';setStatus(error.message||'Stock media search failed.',true);page=Math.max(1,page-(loadMore?1:0));}finally{busy=false;$('btn-stock-search').disabled=false;refreshKeyNotice();}
  }
  function render(items,append){const root=$('stock-media-results');if(!root)return;if(!append)root.innerHTML='';if(!items.length&&!append){root.innerHTML='<div class="stock-empty">No matching stock media found.</div>';return;}for(const item of items){const card=document.createElement('article');card.className='stock-card';card.draggable=true;card.dataset.stockId=item.id;card.innerHTML=`<button type="button" class="stock-preview" title="Preview before download"><img src="${escape(item.thumbnailUrl)}" alt="" loading="lazy"><span>${item.type==='video'?'▶':''}</span><small>${item.width||0}×${item.height||0}${item.duration?` • ${Math.round(item.duration)}s`:''}</small></button><div class="stock-card-info"><strong title="${escape(item.title)}">${escape(item.title)}</strong><a href="${escape(item.pageUrl)}" target="_blank" rel="noopener">${escape(item.attribution)}</a></div><div class="stock-card-actions"><button type="button" data-action="media">Add to Media</button><button type="button" data-action="playhead">At Playhead</button><button type="button" data-action="replace">Replace Slot</button></div>`;
      card.addEventListener('dragstart',event=>{event.dataTransfer.effectAllowed='copy';event.dataTransfer.setData('application/x-cipher-stock',item.id);});card.querySelector('.stock-preview').addEventListener('click',()=>preview(item));card.querySelectorAll('[data-action]').forEach(button=>button.addEventListener('click',()=>runAction(button.dataset.action,item,button)));root.appendChild(card);}}
  function fileName(item,blob){const raw=String(item.title||item.id).replace(/[^a-z0-9 _-]/gi,'').trim().replace(/\s+/g,'_').slice(0,60)||item.id,type=String(blob.type||'').toLowerCase(),ext=item.type==='video'?(type.includes('webm')?'webm':'mp4'):(type.includes('png')?'png':type.includes('webp')?'webp':'jpg');return `${raw}_${item.provider}.${ext}`;}
  async function ensureImported(stockId){const item=results.get(stockId);if(!item)throw new Error('Stock result is no longer available. Search again.');const existing=window.ProTimeline?.getMediaLibrary?.().find(asset=>asset.stockId===item.id);if(existing)return existing;setStatus(`Downloading ${item.type==='video'?'video':'photo'} to local project cache…`);const response=await fetch('/api/stock-media/download',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:item.downloadUrl,provider:item.provider,id:item.id})});if(!response.ok){const error=await response.json().catch(()=>({}));throw new Error(error.error||'Could not download selected stock media.');}const blob=await response.blob(),file=new File([blob],fileName(item,blob),{type:blob.type|| (item.type==='video'?'video/mp4':'image/jpeg'),lastModified:Date.now()}),asset=await window.ProTimeline?.importExternalMediaFile?.(file,{...item,stockId:item.id});if(!asset)throw new Error('Could not add stock media to this project.');setStatus(`${item.attribution} • saved in Project Media.`);return asset;}
  async function runAction(action,item,button){if(button.disabled)return;button.disabled=true;const old=button.textContent;button.textContent='Working…';try{const asset=await ensureImported(item.id);if(action==='playhead')await window.ProTimeline?.addAssetAtPlayhead?.(asset);if(action==='replace'){const index=window.ProTimeline?.getSelectedLegacyIndex?.()??-1;if(index<0)throw new Error('Select a V1 slot first, then choose Replace Slot.');await window.ProTimeline.replaceLegacyScene(index,asset.id);}}catch(error){setStatus(error.message||'Stock media action failed.',true);}finally{button.disabled=false;button.textContent=old;}}
  function preview(item){let modal=$('stock-preview-modal');if(!modal){modal=document.createElement('div');modal.id='stock-preview-modal';modal.className='stock-preview-modal hidden';modal.innerHTML='<div class="stock-preview-dialog"><button type="button" class="stock-preview-close">×</button><div class="stock-preview-stage"></div><div class="stock-preview-meta"></div><div class="stock-preview-actions"><button type="button" data-action="media">Add to Media</button><button type="button" data-action="playhead">Add at Playhead</button><button type="button" data-action="replace">Replace Selected Slot</button></div></div>';document.body.appendChild(modal);modal.querySelector('.stock-preview-close').addEventListener('click',()=>closePreview());modal.addEventListener('click',event=>{if(event.target===modal)closePreview();});}const stage=modal.querySelector('.stock-preview-stage');stage.innerHTML=item.type==='video'?`<video src="${escape(item.previewUrl)}" controls autoplay muted playsinline></video>`:`<img src="${escape(item.previewUrl)}" alt="">`;modal.querySelector('.stock-preview-meta').innerHTML=`<strong>${escape(item.title)}</strong><a href="${escape(item.pageUrl)}" target="_blank" rel="noopener">${escape(item.attribution)}</a><span>${item.width}×${item.height}${item.duration?` • ${Math.round(item.duration)} seconds`:''} • ${escape(item.provider.toUpperCase())}</span>`;modal.querySelectorAll('[data-action]').forEach(button=>button.onclick=()=>runAction(button.dataset.action,item,button));modal.classList.remove('hidden');}
  function closePreview(){const modal=$('stock-preview-modal');modal?.querySelector('video')?.pause?.();modal?.classList.add('hidden');}
  return {init,search,ensureImported,showPane,getResults:()=>results};
})();

document.addEventListener('DOMContentLoaded',()=>window.StockMedia.init());
